(function(){
  const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let activeStop=null;
  function saveBoard(){if(typeof queue==='function')queue()}
  function getStop(){return (S.stops||[]).find(s=>s.id===activeStop)||S.stops?.[0]}
  function ensureUi(){
    if(!$('boardmanage')){const p=$('boardview');const d=document.createElement('div');d.id='boardmanage';d.className='glass panel';d.style.marginBottom='16px';p.parentNode.insertBefore(d,p)}
    if(!$('be-style')){const st=document.createElement('style');st.id='be-style';st.textContent='.boardtime{font:900 32px monospace;color:#ffb300}.boarddest{font:700 20px monospace;color:#ffe09a;margin-top:5px}.boardmeta{font:14px monospace;color:#c99100;margin-top:8px}.boardgrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin-top:24px}.boarditem{padding:16px;border:1px solid #292929;border-radius:17px;background:#0b0b0b}.stopcard{padding:14px;border-radius:18px;background:rgba(255,255,255,.58);border:1px solid #dbe5f0;margin-bottom:10px}.stopcard.active{border-color:#2878f0;background:#eef6ff}.stophead{display:flex;justify-content:space-between;gap:10px;align-items:center}.muted{color:#6d7890}';document.head.appendChild(st)}
  }
  function modal(title,html,fn){$('modal').innerHTML='<div class="modalbg"><div class="modal"><div class="modalhead"><h2>'+title+'</h2><button class="close" id="be-close">×</button></div>'+html+'<div class="actions" style="justify-content:flex-end;margin-top:18px"><button class="btn secondary" id="be-cancel">Отмена</button><button class="btn primary" id="be-save">Сохранить</button></div></div></div>';$('be-close').onclick=$('be-cancel').onclick=()=>$('modal').innerHTML='';$('be-save').onclick=()=>{if(fn()!==false)$('modal').innerHTML=''}}
  function depModal(dep){const s=getStop();if(!s)return;const x=dep||{};modal(dep?'Изменить отправление':'Добавить отправление','<div class="form"><div class="field"><label>Время отправления</label><input class="input" id="be-time" type="time" value="'+esc(x.time||'')+'"></div><div class="field"><label>Номер ПС</label><input class="input" id="be-ps" placeholder="ЭД4м-0482" value="'+esc(x.ps||'')+'"></div><div class="field"><label>Модель ПС</label><input class="input" id="be-model" value="'+esc(x.model||'')+'"></div><div class="field"><label>Направление / рейс</label><input class="input" id="be-dest" placeholder="Максиград — Анапа" value="'+esc(x.dest||'')+'"></div><div class="field"><label>Путь / платформа</label><input class="input" id="be-platform" value="'+esc(x.platform||'')+'"></div><div class="field"><label>Статус</label><select id="be-status"><option>По расписанию</option><option>Посадка</option><option>Отправляется</option><option>Задерживается</option><option>Отменён</option><option>Прибыл</option></select></div><div class="field full"><label>Примечание</label><textarea id="be-note">'+esc(x.note||'')+'</textarea></div></div>',()=>{const v={id:x.id||'dep'+Date.now(),time:$('be-time').value,ps:$('be-ps').value,model:$('be-model').value,dest:$('be-dest').value,platform:$('be-platform').value,status:$('be-status').value,note:$('be-note').value};s.departures=s.departures||[];if(dep)Object.assign(dep,v);else s.departures.push(v);render();saveBoard()});setTimeout(()=>{if($('be-status'))$('be-status').value=x.status||'По расписанию'},0)}
  function render(){ensureUi();S.stops=(S.stops||[]).map(x=>({...x,departures:Array.isArray(x.departures)?x.departures:[]}));const s=getStop();if(s)activeStop=s.id;$('stops').innerHTML=(S.stops||[]).map(x=>'<button class="btn '+(x.id===activeStop?'primary':'secondary')+' small" data-be-stop="'+x.id+'">'+esc(x.name)+'</button>').join('')+'<button class="btn secondary small" data-be-add-stop>＋ Остановка</button>';
    if(!s){$('boardmanage').innerHTML='<div class="card">Сначала создай остановку.</div>';$('boardview').innerHTML='<div class="boardhead"><span>УЖДФОТО</span><span>ТАБЛО</span></div><div class="boardname">НЕТ ОСТАНОВОК</div>';return}
    const d=[...(s.departures||[])].sort((a,b)=>(a.time||'').localeCompare(b.time||''));
    $('boardmanage').innerHTML='<div class="hero" style="padding:0 0 14px;margin:0"><div><h2>🚉 '+esc(s.name)+'</h2><p>Расписание остановки — время, ПС, направление, путь и статус.</p></div><div class="actions"><button class="btn primary" data-be-add-dep>＋ Добавить отправление</button><button class="btn secondary" data-be-edit-stop>✏️ Переименовать</button><button class="btn danger" data-be-del-stop>🗑 Удалить остановку</button></div></div>'+(d.length?'<div class="table"><table><thead><tr><th>Время</th><th>ПС</th><th>Модель</th><th>Направление</th><th>Путь</th><th>Статус</th><th>Примечание</th><th>Действия</th></tr></thead><tbody>'+d.map(x=>'<tr><td><b>'+esc(x.time||'--:--')+'</b></td><td>'+esc(x.ps||'—')+'</td><td>'+esc(x.model||'—')+'</td><td>'+esc(x.dest||'—')+'</td><td>'+esc(x.platform||'—')+'</td><td>'+esc(x.status||'По расписанию')+'</td><td>'+esc(x.note||'')+'</td><td><button class="btn secondary small" data-be-edit-dep="'+x.id+'">✏️</button> <button class="btn danger small" data-be-del-dep="'+x.id+'">🗑</button></td></tr>').join('')+'</tbody></table></div>':'<div class="card">Пока нет отправлений. Нажми «Добавить отправление».</div>');
    $('boardview').innerHTML='<div class="boardhead"><span>УЖДФОТО / ГОРОДСКОЙ ТРАНСПОРТ</span><span>СТАНЦИЯ</span></div><div class="dottext">ОТПРАВЛЕНИЯ</div><div class="boardname">'+esc(s.name)+'</div><div class="boardgrid">'+(d.length?d.map(x=>'<div class="boarditem"><div class="boardtime">'+esc(x.time||'--:--')+'</div><div class="boarddest">'+esc(x.dest||'Без направления')+'</div><div class="boardmeta">ПС: '+esc(x.ps||'—')+(x.model?' · '+esc(x.model):'')+'<br>Путь: '+esc(x.platform||'—')+' · '+esc(x.status||'По расписанию')+(x.note?'<br>'+esc(x.note):'')+'</div></div>').join(''):'<div class="boarditem"><div class="dottext">НЕТ ОТПРАВЛЕНИЙ</div><div style="margin-top:12px;color:#c99100;font:16px monospace">Добавь первое отправление в панели управления.</div></div>')+'</div>';
  }
  document.addEventListener('click',function(e){
    const st=e.target.closest('[data-be-stop]');if(st){activeStop=st.dataset.beStop;render();return}
    if(e.target.closest('[data-be-add-stop]')){modal('Новая остановка','<div class="field"><label>Название остановки / станции</label><input class="input" id="be-stop-name" placeholder="Анапа"></div>',()=>{const n=$('be-stop-name').value.trim();if(!n)return false;const s={id:'s'+Date.now(),name:n,departures:[]};S.stops=S.stops||[];S.stops.unshift(s);activeStop=s.id;render();saveBoard()});return}
    if(e.target.closest('[data-be-add-dep]')){depModal();return}
    const ed=e.target.closest('[data-be-edit-dep]');if(ed){const s=getStop(),d=s?.departures?.find(x=>x.id===ed.dataset.beEditDep);if(d)depModal(d);return}
    const dl=e.target.closest('[data-be-del-dep]');if(dl){const s=getStop();if(s){s.departures=(s.departures||[]).filter(x=>x.id!==dl.dataset.beDelDep);render();saveBoard()}return}
    if(e.target.closest('[data-be-edit-stop]')){const s=getStop();if(s)modal('Переименовать остановку','<div class="field"><label>Название</label><input class="input" id="be-new-stop" value="'+esc(s.name)+'"></div>',()=>{s.name=$('be-new-stop').value.trim()||s.name;render();saveBoard()});return}
    if(e.target.closest('[data-be-del-stop]')){const s=getStop();if(s&&confirm('Удалить остановку вместе со всеми отправлениями?')){S.stops=S.stops.filter(x=>x.id!==s.id);activeStop=S.stops[0]?.id||null;render();saveBoard()}return}
    if(e.target.closest('[data-action="add-stop"]'))setTimeout(render,80);
    if(e.target.closest('[data-page="board"]'))setTimeout(render,80);
  });
  window.addEventListener('load',()=>setTimeout(()=>{activeStop=S.stops?.[0]?.id||null;render()},300));
})();
