/* Максиградская железная дорога — Новости */
(function(){
  'use strict';
  const KEY='maxigrad_news_v1';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}};
  const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
  function styles(){if(document.getElementById('mgn-style'))return;const s=document.createElement('style');s.id='mgn-style';s.textContent=`
#mgNewsPage{display:none}.mgn-wrap{max-width:1100px;margin:auto}.mgn-editor,.mgn-card{background:var(--bp-card-bg);border:1px solid var(--bp-border);border-radius:8px;padding:16px;margin-bottom:14px}.mgn-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.mgn-editor input,.mgn-editor textarea,.mgn-editor select{width:100%;box-sizing:border-box;padding:9px;border:1px solid var(--bp-border);border-radius:5px;background:var(--bp-input-bg);color:var(--bp-text)}.mgn-editor textarea{min-height:120px;resize:vertical}.mgn-span{grid-column:1/-1}.mgn-card h3{margin:0 0 7px}.mgn-meta{font-size:11px;color:var(--bp-text-muted);margin-bottom:9px}.mgn-body{white-space:pre-wrap;line-height:1.5}.mgn-actions{display:flex;gap:7px;margin-top:12px}.mgn-empty{text-align:center;color:var(--bp-text-muted);padding:35px}.mgn-pin{border-left:4px solid var(--bp-accent-gold)}@media(max-width:650px){.mgn-grid{grid-template-columns:1fr}.mgn-span{grid-column:auto}}
`;document.head.appendChild(s)}
  function page(){if(document.getElementById('mgNewsPage'))return;const d=document.createElement('div');d.id='mgNewsPage';d.className='main-wrapper';d.innerHTML=`<div class="mgn-wrap"><div class="page-header"><span>📰 Новости Максиграда</span><div class="action-buttons"><button class="btn-secondary" id="mgnBack">← Назад</button><button class="btn-primary" id="mgnNew">＋ Написать новость</button></div></div><div id="mgnEditor" class="mgn-editor" style="display:none"><div class="mgn-grid"><div><label>Заголовок</label><input id="mgnTitle" maxlength="120" placeholder="Например: Изменение движения поездов"></div><div><label>Категория</label><select id="mgnCat"><option>Важное</option><option>Транспорт</option><option>Железная дорога</option><option>Город</option><option>Объявление</option></select></div><div class="mgn-span"><label>Текст новости</label><textarea id="mgnText" placeholder="Напишите сообщение для жителей города..."></textarea></div><div><label>Автор</label><input id="mgnAuthor" value="Максиградская железная дорога"></div><div style="display:flex;align-items:end"><label><input type="checkbox" id="mgnPinned"> Закрепить новость сверху</label></div></div><div class="mgn-actions"><button class="btn-primary" id="mgnSave">Опубликовать</button><button class="btn-secondary" id="mgnCancel">Отмена</button></div></div><div id="mgnList"></div></div>`;document.body.appendChild(d)}
  function render(){const list=document.getElementById('mgnList');let a=load().sort((x,y)=>Number(y.pinned)-Number(x.pinned)||y.created-x.created);list.innerHTML=a.length?a.map(n=>`<article class="mgn-card ${n.pinned?'mgn-pin':''}"><h3>${esc(n.title)}</h3><div class="mgn-meta">${esc(n.category)} · ${new Date(n.created).toLocaleString('ru-RU')} · ${esc(n.author||'')}</div><div class="mgn-body">${esc(n.text)}</div><div class="mgn-actions"><button class="btn-secondary btn-sm" data-edit="${n.id}">✏️ Редактировать</button><button class="btn-danger btn-sm" data-del="${n.id}">🗑 Удалить</button></div></article>`).join(''):'<div class="mgn-empty">Новостей пока нет. Нажмите «Написать новость», чтобы создать первую.</div>'}
  let edit=null;
  function editor(show=true,n=null){const e=document.getElementById('mgnEditor');e.style.display=show?'block':'none';if(show){edit=n?.id||null;document.getElementById('mgnTitle').value=n?.title||'';document.getElementById('mgnCat').value=n?.category||'Важное';document.getElementById('mgnText').value=n?.text||'';document.getElementById('mgnAuthor').value=n?.author||'Максиградская железная дорога';document.getElementById('mgnPinned').checked=!!n?.pinned;document.getElementById('mgnTitle').focus()}}
  function saveNews(){const title=document.getElementById('mgnTitle').value.trim(),text=document.getElementById('mgnText').value.trim();if(!title||!text){alert('Заполните заголовок и текст новости.');return}let a=load(),n={id:edit||Date.now(),title,text,category:document.getElementById('mgnCat').value,author:document.getElementById('mgnAuthor').value.trim(),pinned:document.getElementById('mgnPinned').checked,created:edit?(a.find(x=>x.id===edit)?.created||Date.now()):Date.now()};if(edit){const i=a.findIndex(x=>x.id===edit);if(i>=0)a[i]=n}else a.push(n);save(a);editor(false);render()}
  function open(){document.querySelectorAll('.main-wrapper').forEach(x=>{if(x.id!=='mgNewsPage')x.style.display='none'});document.getElementById('mgNewsPage').style.display='block';document.querySelectorAll('.nav-tab-btn').forEach(x=>x.classList.remove('active'));document.getElementById('mgnBtn')?.classList.add('active');render()}
  function back(){document.getElementById('mgNewsPage').style.display='none';if(typeof switchPage==='function')switchPage('schedule');else document.querySelector('.main-wrapper')?.style.removeProperty('display')}
  function init(){styles();page();const h=document.querySelector('header .header-controls');if(h&&!document.getElementById('mgnBtn')){const b=document.createElement('button');b.id='mgnBtn';b.className='nav-tab-btn';b.textContent='📰 Новости';b.onclick=open;h.insertBefore(b,h.firstChild)}document.getElementById('mgnBack').onclick=back;document.getElementById('mgnNew').onclick=()=>editor(true);document.getElementById('mgnCancel').onclick=()=>editor(false);document.getElementById('mgnSave').onclick=saveNews;document.getElementById('mgnList').onclick=e=>{const ed=e.target.closest('[data-edit]'),de=e.target.closest('[data-del]');const a=load();if(ed){const n=a.find(x=>String(x.id)===ed.dataset.edit);if(n)editor(true,n)}if(de&&confirm('Удалить эту новость?')){save(a.filter(x=>String(x.id)!==de.dataset.del));render()}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,900));else setTimeout(init,900);
  if(!document.querySelector('script[data-rgmap]')){const s=document.createElement('script');s.src='railphoto-map.js?v=1';s.dataset.rgmap='1';document.body.appendChild(s)}
})();